[package]
name = "note-app"
version = "0.1.0"
authors = ["youngtrashbag"]
edition = "2018"
license = "MIT"
description = "backend of note taking app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
